### PR TITLE
src: Check for SSSE3 support at runtime

### PR DESCRIPTION
**Pull request by endrift**
Untested fix for #187

Please make sure it doesn't cause significant slowdown in imageops calls.

### CODE REVIEW

**Comment by christopherhesse** [comment]
Thanks!  Hopefully I can test it out next time we do open source stuff.

**Comment by endrift** [comment]
Looks like it doesn't build on clang, which I forgot we used on macOS.

**Review by crypt096 — CHANGES_REQUESTED** [review]
Build has failed. Please investigate reasons.

**Comment by endrift** [comment]
The build failures seem to just be related to the outdated version of macOS in use, not the changes.

**Comment by christopherhesse** [comment]
Thanks for the PR @endrift!  I think not many people use these CPUs so I'm going to close this for now.

**Pull request closed without merging**
