### PR TITLE
python 3.8

### LINKED ISSUE #197: add python 3.8 wheels
* [x] add python 3.8 to build scripts
* [x] build new docker images with python 3.8
* [x] update docs
* [x] include readme in setup.py long description
* [x] increment version
* [ ] test wheels
* [ ] upload wheels

### PR DESCRIPTION
**Pull request by christopherhesse**
fixes #197

### CODE REVIEW

**Comment by christopherhesse** [comment]
@endrift seems like python's `dev.msi` for python 3.8 does not include `libpython.a` only `python.lib`, any ideas on how to workaround that?

**Comment by christopherhesse** [comment]
It seems like there might be different rules for linking against libpython for 3.8: https://docs.python.org/3/whatsnew/3.8.html#debug-build-uses-the-same-abi-as-release-build

**Comment by endrift** [comment]
@christopherhesse not sure if it'll still link properly, but you might be able to just rename it to `libpython.a`. They're in the same format, it's just the lib file is targeted for MSVC.

**Comment by christopher-hesse** [comment]
here's a converted one from https://code.google.com/archive/p/lib2a/ in case that does not work [convert.zip](https://github.com/openai/retro/files/4532425/convert.zip)

**Comment by christopher-hesse** [comment]
another option:

from https://stackoverflow.com/questions/11793370/how-can-i-convert-a-vsts-lib-to-a-mingw-a

```
curl -O https://www.python.org/ftp/python/3.8.2/amd64/core.msi
7z x core.msi
apt-get install --yes apt-get install mingw-w64-tools
gendef python.dll
/usr/bin/x86_64-w64-mingw32-dlltool --as-flags=--64 -m i386:x86-64 -k --output-lib libpython.a --input-def python.def
```

**Comment by christopherhesse** [comment]
Thanks for the suggestion @endrift!  I couldn't get that to work but the dlltool thing at least finished compiling.

**Pull request merged**
