### PR TITLE
Memory leak fix.

### PR DESCRIPTION
**Pull request by eaplatanios**
This is pulled out of #152 as @endrift suggested. I'm not sure if it's ok now even though I get no errors when I check it with valgrind (I was getting errors when I wasn't using `strdup`). Who is supposed to own the memory pointed to by `data` and free it? @endrift do you have any suggestions?

### CODE REVIEW

**Comment by christopherhesse** [comment]
It's not clear to me what `RETRO_ENVIRONMENT_GET_SYSTEM_DIRECTORY` is used for, could this just return like the path to the directory that the retro shared object is in?

**Comment by eaplatanios** [comment]
@endrift @christopherhesse I made the requested change. Could you please take another look?

Also, what is role of `atari-py` relative to `retro`? If one wants to play around with atari environments which one do you recommend using and why?

**Comment by christopherhesse** [comment]
Retro is nice if you want consistency with other retro games, but ALE is faster, see https://github.com/openai/retro/issues/127

**Comment by eaplatanios** [comment]
Thanks for the quick response! Are there plans to tackle the issues mentioned in that post? Also, when you say faster, what kind of difference have you measured? Is it significant?

**Comment by christopherhesse** [comment]
I don't remember, but I believe it is significant, something like 2-3x faster per frame for ALE.

**Comment by christopherhesse** [comment]
Thanks @endrift and @eaplatanios!

**Pull request merged**
