### PR TITLE
add observation type RAM

### PR DESCRIPTION
**Pull request by tycho01**
inspired by Gym's [Atari Env](https://github.com/openai/gym/blob/master/gym/envs/atari/atari_env.py).
helps find out:
- what can be achieved using RAM input
- what challenges differ from image input
- whether it helps to train on image -> RAM -> action vs just image -> action directly

### CODE REVIEW

**Comment by christopherhesse** [comment]
I think this is an interesting idea, but uses the size of emulator state as the size of ram and I'm not sure this works with the current dict format of data.memory.  Do you have any interest in updating this PR @tycho01 ?

**Comment by endrift** [comment]
Yeah, states and RAM are different. Some states are even compressed, so that wouldn't be workable in the first place.

**Comment by tycho01** [comment]
> Some states are even compressed, so that wouldn't be workable in the first place.

hm, that does seem unfortunate. would you know if the affected portion of the roms presently used would be significant?

@endrift:

> `shape = (len(self.em.get_state()),)`

> [this] uses the size of emulator state as the size of ram and I'm not sure this works with the current dict format of data.memory.

oh. I'm not super familiar with the format used there. would you know what that's like? from [`get_state`](https://github.com/openai/retro/blob/d1188359cf7abcaf0dbd33b82276df55d5298ea2/src/retro.cpp#L51-L56) I couldn't quite make out anything about that. if I know what to do I'd gladly fix that.

**Comment by endrift** [comment]
> would you know if the affected portion of the roms presently used would be significant?
I believe every single SNES game and possibly every single Genesis game, but I can't remember offhand.

Also state sizes can vary, so...yeah

**Comment by tycho01** [comment]
okay, I'll close this PR then. if we find a way around these issues, I guess we can open a new one.

**Comment by christopherhesse** [comment]
I think you don't use `get_state` at all, just use `data.memory`, reduce it to a single `np.ndarray` and use the size of that.

**Comment by tycho01** [comment]
@christopherhesse thanks, I've updated it to directly use the shape of `data.memory` now.

**Comment by christopherhesse** [comment]
Your code had some errors in it, so I made a new PR: https://github.com/openai/retro/pull/112 and we should move discussion over there.

Thanks for filing this PR!

**Pull request closed without merging**
